on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Gnkry-Auth-Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: ls -al